# Generated by Django 5.0.6 on 2024-05-27 08:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("FaceASAP", "0002_videoencoding_faceencoding"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="faceencoding",
            name="user",
        ),
    ]
